version: 1
workers:
- name: gohci-u3
  checks:
  - cmd:
    - /home/gohci/repo-info.sh
  - cmd:
    - ./board/gohci.sh
  - cmd:
    - ./mqtt-async/gohci.sh
  - cmd:
    - ./mqrepl/gohci.sh
  - cmd:
    - /home/gohci/repo-save.sh
