version: 1
workers:
- name: gohci-u3
  checks:
  - cmd:
    - timeout
    - 3m
    - ./gohci.sh
  - cmd:
    - timeout
    - 3m
    - ./board/gohci.sh
  - cmd:
    - timeout
    - 3m
    - ./mqtt_async/gohci.sh
  - cmd:
    - timeout
    - 3m
    - ./mqrepl/gohci.sh
  - cmd:
    - timeout
    - 3m
    - ./mqboard/gohci.sh
  - cmd:
    - timeout
    - 3m
    - /home/gohci/repo-save.sh
